import StoryContainer from 'container/StoryContainer';
import Head from 'next/head';
import React from 'react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-520 mx-auto">
        <StoryContainer />
      </main>
    </div>
  );
}
